// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrlVZnKyVi2seJNN9oLEe6Z0SVAOq1MU',
    appId: '1:863880810753:web:d5e047ee756063a46dcb00',
    messagingSenderId: '863880810753',
    projectId: 'digitalworld-8fcf2',
    authDomain: 'digitalworld-8fcf2.firebaseapp.com',
    storageBucket: 'digitalworld-8fcf2.appspot.com',
    measurementId: 'G-J5JPY32XNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZdwMTPftWql0GeeesnwiUQDJ2SV3Kw8',
    appId: '1:863880810753:android:952017ba4e63d9296dcb00',
    messagingSenderId: '863880810753',
    projectId: 'digitalworld-8fcf2',
    storageBucket: 'digitalworld-8fcf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClsEw9ciay04DGiCGWngZ7gRkPB93puXQ',
    appId: '1:863880810753:ios:de7a51386a48c4a66dcb00',
    messagingSenderId: '863880810753',
    projectId: 'digitalworld-8fcf2',
    storageBucket: 'digitalworld-8fcf2.appspot.com',
    iosBundleId: 'com.example.digitalworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClsEw9ciay04DGiCGWngZ7gRkPB93puXQ',
    appId: '1:863880810753:ios:de7a51386a48c4a66dcb00',
    messagingSenderId: '863880810753',
    projectId: 'digitalworld-8fcf2',
    storageBucket: 'digitalworld-8fcf2.appspot.com',
    iosBundleId: 'com.example.digitalworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALrlVZnKyVi2seJNN9oLEe6Z0SVAOq1MU',
    appId: '1:863880810753:web:9ab0542166d622da6dcb00',
    messagingSenderId: '863880810753',
    projectId: 'digitalworld-8fcf2',
    authDomain: 'digitalworld-8fcf2.firebaseapp.com',
    storageBucket: 'digitalworld-8fcf2.appspot.com',
    measurementId: 'G-XHMVLQRCED',
  );
}
